# dependabot.yml

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      time: "09:00"
      interval: daily
      timezone: Asia/Kolkata
    ignore:
        # These are peer deps of Cargo and should not be automatically bumped
        - dependency-name: "semver"
        - dependency-name: "crates-io"
    reviewers:
      - aaqaishtyaq
    open-pull-requests-limit: 99
    rebase-strategy: "disabled"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      time: "09:00"
      interval: daily
      timezone: Asia/Kolkata
    reviewers:
      - aaqaishtyaq
    open-pull-requests-limit: 99
